### ISSUE TITLE
Shortcode dosen't display frontend form

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-resend-receipt#1]
I haven't had a chance to properly debug this issue, but for whatever reason the short-code isn't showing the actual form on the frontend even when resend receipt functionality is enabled on a per-product basis.

I am using latest EDD and Themedd.

**Comment by pippinsplugins** [comment]
@davidsherlock Have you enabled the resend option on the product? It needs to be enabled for each product.

**Comment by SDavisMedia** [comment]
This commit breaks the shortcode output: https://github.com/easydigitaldownloads/edd-resend-receipt/commit/d7cbc862f914cc6aeefe622ae2491a5a9fad4222

This check specifically: https://github.com/easydigitaldownloads/edd-resend-receipt/blob/master/includes/functions.php#L88

Gonna figure out why that commit was made and fix this. The plugin's pretty much useless with this bug.

**Comment by SDavisMedia** [comment]
I believe the goal of this commit https://github.com/easydigitaldownloads/edd-resend-receipt/commit/d7cbc862f914cc6aeefe622ae2491a5a9fad4222 was to check and see if a download should be eligible for resending receipts. However, the way it goes about checking just doesn't make sense to me. Everything about the check is based on the page where the shortcode resides... not any particular download.

Furthermore, I think the individual product setting for enabling (default) and disabling resend was built with the idea that purchase receipts would only have a single product. However, there was still code in place that checked to see how many of the products included in a purchase have disabled resending. It just didn't seem to use that information in a logical way.

My PR reverses the aforementioned commit and then adjusts the code to behave as I believe it was originally intended:

* If all products on the purchase are eligible for resend, then resend.
* If some products on the purchase are eligible for resend, but others are not, resend.
* If all products on the purchase have disabled resending, whether there's one or several, do not resend.
