### ISSUE TITLE
Shortcode output invalid

### ISSUE THREAD

**Issue by shaynesanderson** [easydigitaldownloads/edd-resend-receipt#10]
The opening div on the [edd_resend_form] is echoed outside the ob_start, so it appears in the wrong place. See edd-resend-receipt/includes/function.php line 98.

Current:

	<div class="edd-resend-div <?php echo $class; ?>">
		<?php
		ob_start();
		echo '<form action="'.$_SERVER['REQUEST_URI'].'" method="post" id="eddrr-form">';

Updated:

	
		<?php
		ob_start();
                 echo '<div class="edd-resend-div <?php echo $class; ?>">';
		echo '<form action="'.$_SERVER['REQUEST_URI'].'" method="post" id="eddrr-form">';
                echo '</div>';

Reference: https://secure.helpscout.net/conversation/1270227580/164539?folderId=180499

**Comment by ashleyfae** [comment]
Closing this as I accidentally created a new issue. See #17
